# Generated by Django 3.0.4 on 2020-03-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_tags_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
