# Generated by Django 3.0.4 on 2020-03-16 18:31

import custom_user_tags_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_tags_app', '0002_user_random_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=custom_user_tags_app.models.get_random_number),
        ),
    ]
